// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchF3ENidM7Z7n-3PvKMydmXy_pY8I1NU',
    appId: '1:946594005667:web:feefb358190eafa078b516',
    messagingSenderId: '946594005667',
    projectId: 'ayursadan-ecommerceapp',
    authDomain: 'ayursadan-ecommerceapp.firebaseapp.com',
    storageBucket: 'ayursadan-ecommerceapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDizHg1jncYJFhqlIR4SRyR1OfbMiFzc_E',
    appId: '1:946594005667:android:d2fb417b92a366b778b516',
    messagingSenderId: '946594005667',
    projectId: 'ayursadan-ecommerceapp',
    storageBucket: 'ayursadan-ecommerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfrdzt_dQnDYlIO8c8I8565ULlxHKVrNY',
    appId: '1:946594005667:ios:72de5f2eae2d446978b516',
    messagingSenderId: '946594005667',
    projectId: 'ayursadan-ecommerceapp',
    storageBucket: 'ayursadan-ecommerceapp.appspot.com',
    iosClientId: '946594005667-b8663467g2de1k5mtf9vo88mjuf4gntl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfrdzt_dQnDYlIO8c8I8565ULlxHKVrNY',
    appId: '1:946594005667:ios:72de5f2eae2d446978b516',
    messagingSenderId: '946594005667',
    projectId: 'ayursadan-ecommerceapp',
    storageBucket: 'ayursadan-ecommerceapp.appspot.com',
    iosClientId: '946594005667-b8663467g2de1k5mtf9vo88mjuf4gntl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
